name: counting_set
description: A package providing a set that requires an element to be removed as many times as it was added.
version: 0.1.1
homepage: https://github.com/hacker1024/counting_set.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.8
